baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Awesome Inc.'
theme = "ananke"
publishDir = './dist'

[module]
[[module.imports]]
	path = "github.com/theNewDynamic/gohugo-theme-ananke"
